spring:
  application:
    name: gateway-service
  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/product/**
          
      - id: order-service
        uri: lb://order-service
        predicates:
          - Path=/orders/**

          

server : 
  port : 9999
  
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka